sudo: false

language:
    - php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
  # Branch for patches against 2.x. `master` is now 3.x which WPCS is not (yet) compatible with.
  - PHPCS_BRANCH=2.9
  # Tagged release
  - PHPCS_BRANCH=2.9.0

matrix:
  fast_finish: true
  include:
    # Run PHPCS against WPCS. I just picked to run it against 5.5.
    - php: 5.5
      env: PHPCS_BRANCH=2.9 SNIFF=1
    # Run against PHPCS 3.0. I just picked to run it against 5.6.
    - php: 5.6
      env: PHPCS_BRANCH=master
    # Run against HHVM and PHP nightly.
    - php: hhvm
      sudo: required
      dist: trusty 
      group: edge
      env: PHPCS_BRANCH=2.9
    - php: nightly
      env: PHPCS_BRANCH=2.9
  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm
    - env: PHPCS_BRANCH=master

before_install:
    - export XMLLINT_INDENT="	"
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPUNIT_DIR=/tmp/phpunit
    - export PHPCS_BIN=$(if [[ $PHPCS_BRANCH == master ]]; then echo $PHPCS_DIR/bin/phpcs; else echo $PHPCS_DIR/scripts/phpcs; fi)
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - $PHPCS_BIN --config-set installed_paths $(pwd)
    # Download PHPUnit 5.x for builds on PHP 7, nightly and HHVM as
    # PHPCS test suite is currently not compatible with PHPUnit 6.x.
    - if [[ ${TRAVIS_PHP_VERSION:0:2} != "5." ]]; then wget -P $PHPUNIT_DIR https://phar.phpunit.de/phpunit-5.7.phar && chmod +x $PHPUNIT_DIR/phpunit-5.7.phar; fi

script:
    # Lint the PHP files against parse errors.
    - if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
    # Run the unit tests.
    - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:2} != "5." ]]; then php $PHPUNIT_DIR/phpunit-5.7.phar --filter WordPress /tmp/phpcs/tests/AllTests.php; fi
    # WordPress Coding Standards.
    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    # @link http://pear.php.net/package/PHP_CodeSniffer/
    # -p flag: Show progress of the run.
    # -s flag: Show sniff codes in all reports.
    # -v flag: Print verbose output.
    # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
    # --standard: Use WordPress as the standard.
    # --extensions: Only sniff PHP files.
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -n . --standard=./bin/phpcs.xml --extensions=php; fi
    # Validate the xml files.
    # @link http://xmlsoft.org/xmllint.html
    - if [[ "$SNIFF" == "1" ]]; then xmllint --noout ./*/ruleset.xml; fi
    - if [[ "$SNIFF" == "1" ]]; then xmllint --noout ./project.ruleset.xml.example; fi
    # Check the code-style consistency of the xml files.
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./WordPress/ruleset.xml <(xmllint --format "./WordPress/ruleset.xml"); fi
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./WordPress-Core/ruleset.xml <(xmllint --format "./WordPress-Core/ruleset.xml"); fi
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./WordPress-Docs/ruleset.xml <(xmllint --format "./WordPress-Docs/ruleset.xml"); fi
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./WordPress-Extra/ruleset.xml <(xmllint --format "./WordPress-Extra/ruleset.xml"); fi
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./WordPress-VIP/ruleset.xml <(xmllint --format "./WordPress-VIP/ruleset.xml"); fi
    - if [[ "$SNIFF" == "1" ]]; then diff -B --tabsize=4 ./project.ruleset.xml.example <(xmllint --format "./project.ruleset.xml.example"); fi
