sudo: false

language:
    - php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - PHPCS_BRANCH=master
  - PHPCS_BRANCH=2.2.0

matrix:
  fast_finish: true
  include:
    # Run against PHPCS 3.0. I just picked to run it against 5.6.
    - php: 5.6
      env: PHPCS_BRANCH=3.0
    # Run against HHVM and PHP nightly.
    - php: hhvm
      env: PHPCS_BRANCH=master
    - php: nightly
      env: PHPCS_BRANCH=master
  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm
    - env: PHPCS_BRANCH=3.0

install:
    - export DEV_LIB_PATH=dev-lib
    - export DEV_LIB_SKIP=composer
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - export PHPCS_DIR=/tmp/phpcs
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - export PHPCS_BIN_DIR=$(if [[ $PHPCS_BRANCH == 3.0 ]]; then echo $PHPCS_DIR/bin; else echo $PHPCS_DIR/scripts; fi)
    - export PATH="$PHPCS_BIN_DIR:$PATH"
    - phpcs --config-set installed_paths $(pwd)
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh
